procutils: Move py3 compat raise() to its own function
Apparently using exec() in a function that uses a closure is a syntax error:
    SyntaxError: unqualified exec is not allowed in function 'cmd' because it contains a nested function with free variables